name: bostonbyboston
favicon: null
layout_spectrum: 0.12532304739579558
typography_spectrum: 0.6893863684963435
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4987398360390216
  lightness: 0.35503576695919037
  saturation: 0.26041802880354226
  rhythmicContrast: 0.22676906967535615
purpose: []
